CREATE TABLE `dialect_area` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`dialect_region_id` integer NOT NULL,
	`source_code` text NOT NULL,
	`name` text NOT NULL,
	`sort_order` integer NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	FOREIGN KEY (`dialect_region_id`) REFERENCES `dialect_region`(`id`) ON UPDATE no action ON DELETE restrict
);
--> statement-breakpoint
CREATE UNIQUE INDEX `dialect_area_region_source_uidx` ON `dialect_area` (`dialect_region_id`,`source_code`);--> statement-breakpoint
CREATE INDEX `dialect_area_region_active_sort_idx` ON `dialect_area` (`dialect_region_id`,`is_active`,`sort_order`);--> statement-breakpoint
CREATE TABLE `dialect_region` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`code` text NOT NULL,
	`name` text NOT NULL,
	`sort_order` integer NOT NULL,
	`is_active` integer DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `dialect_region_code_unique` ON `dialect_region` (`code`);--> statement-breakpoint
CREATE INDEX `dialect_region_active_sort_idx` ON `dialect_region` (`is_active`,`sort_order`);--> statement-breakpoint

-- Source: Ordbok över Finlands svenska folkmål, "Ortnamnsförkortningar och dialektområden".
-- https://kaino.kotus.fi/fo/?p=abbreviations#abb_ortnamn
INSERT INTO `dialect_region` (`id`, `code`, `name`, `sort_order`) VALUES
	(1, 'norra-osterbotten', 'Norra Österbotten', 1),
	(2, 'mellersta-osterbotten', 'Mellersta Österbotten', 2),
	(3, 'sodra-osterbotten', 'Södra Österbotten', 3),
	(4, 'satakunta', 'Satakunta', 4),
	(5, 'vastra-aland', 'Västra Åland', 5),
	(6, 'ostra-aland', 'Östra Åland', 6),
	(7, 'vastra-aboland', 'Västra Åboland', 7),
	(8, 'ostra-aboland', 'Östra Åboland', 8),
	(9, 'vastra-nyland', 'Västra Nyland', 9),
	(10, 'mellersta-nyland', 'Mellersta Nyland', 10),
	(11, 'ostra-nyland', 'Östra Nyland', 11);--> statement-breakpoint

INSERT INTO `dialect_area` (`dialect_region_id`, `source_code`, `name`, `sort_order`) VALUES
	(1, 'Kb', 'Karleby', 1),
	(1, 'Nv', 'Nedervetil', 2),
	(1, 'Tj', 'Terjärv', 3),
	(1, 'Kr', 'Kronoby', 4),
	(1, 'Öj', 'Öja', 5),
	(1, 'La', 'Larsmo', 6),
	(1, 'Ee', 'Esse', 7),
	(1, 'Pe', 'Pedersöre', 8),
	(1, 'Pu', 'Purmo', 9),
	(1, 'Nb', 'Nykarleby', 10),
	(1, 'Je', 'Jeppo', 11),
	(1, 'Mu', 'Munsala', 12),
	(2, 'Or', 'Oravais', 1),
	(2, 'Vö', 'Vörå', 2),
	(2, 'Mm', 'Maxmo', 3),
	(2, 'Kv', 'Kvevlax', 4),
	(2, 'Bj', 'Björköby', 5),
	(2, 'Re', 'Replot', 6),
	(2, 'Kh', 'Korsholm', 7),
	(2, 'Sv', 'Solf', 8),
	(3, 'Ma', 'Malax', 1),
	(3, 'Be', 'Bergö', 2),
	(3, 'Pl', 'Petalax', 3),
	(3, 'Pö', 'Pörtom', 4),
	(3, 'Kn', 'Korsnäs', 5),
	(3, 'Öv', 'Övermark', 6),
	(3, 'Nä', 'Närpes', 7),
	(3, 'Tk', 'Tjöck', 8),
	(3, 'Lf', 'Lappfjärd', 9),
	(3, 'Sb', 'Sideby', 10),
	(4, 'Sm', 'Sastmola', 1),
	(4, 'Vb', 'Vittisbofjärd', 2),
	(5, 'Ec', 'Eckerö', 1),
	(5, 'Ha', 'Hammarland', 2),
	(5, 'Ge', 'Geta', 3),
	(5, 'Fi', 'Finström', 4),
	(5, 'Jo', 'Jomala', 5),
	(5, 'Mh', 'Mariehamn', 6),
	(5, 'Sa', 'Saltvik', 7),
	(5, 'Su', 'Sund', 8),
	(5, 'Vå', 'Vårdö', 9),
	(5, 'Le', 'Lemland', 10),
	(5, 'Lu', 'Lumparland', 11),
	(6, 'Kö', 'Kökar', 1),
	(6, 'Fö', 'Föglö', 2),
	(6, 'So', 'Sottunga', 3),
	(6, 'Ku', 'Kumlinge', 4),
	(6, 'Bö', 'Brändö', 5),
	(7, 'Iö', 'Iniö', 1),
	(7, 'Ho', 'Houtskär', 2),
	(7, 'Ko', 'Korpo', 3),
	(7, 'Na', 'Nagu', 4),
	(7, 'Pa', 'Pargas', 5),
	(8, 'Pa', 'Pargas', 1),
	(8, 'Ki', 'Kimito', 2),
	(8, 'Df', 'Dragsfjärd', 3),
	(8, 'Vf', 'Västanfjärd', 4),
	(8, 'Hi', 'Hitis', 5),
	(8, 'Fb', 'Finby', 6),
	(9, 'Br', 'Bromarv', 1),
	(9, 'Te', 'Tenala', 2),
	(9, 'Po', 'Pojo', 3),
	(9, 'En', 'Ekenäs', 4),
	(9, 'Sn', 'Snappertuna', 5),
	(9, 'Ka', 'Karis', 6),
	(9, 'Kl', 'Karislojo', 7),
	(9, 'Lo', 'Lojo', 8),
	(9, 'Iå', 'Ingå', 9),
	(9, 'Db', 'Degerby', 10),
	(10, 'Sj', 'Sjundeå', 1),
	(10, 'Ky', 'Kyrkslätt', 2),
	(10, 'Es', 'Esbo', 3),
	(10, 'Hf', 'Helsingfors', 4),
	(10, 'He', 'Helsinge', 5),
	(10, 'Tu', 'Tusby', 6),
	(10, 'Hj', 'Hausjärvi', 7),
	(11, 'Si', 'Sibbo', 1),
	(11, 'Bo', 'Borgå', 2),
	(11, 'Pä', 'Pernå', 3),
	(11, 'Li', 'Liljendal', 4),
	(11, 'Mö', 'Mörskom', 5),
	(11, 'Lt', 'Lappträsk', 6),
	(11, 'St', 'Strömfors', 7),
	(11, 'El', 'Elimä', 8),
	(11, 'Py', 'Pyttis', 9);
